name: docs_gh_pages

on:
  push:
    branches: [master]

jobs:
  docs_gh_page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: peterhs73/sphinx-docs-action@v0.0.1
        with:
          python-version: 3.10 
          pyproject-path: pyproject.toml # defaults to pyproject.toml
          docs-source: docs/ # defaults to docs/
          docs-build: docs_build/ # defaults to docs_build/
          external-repo: <username>/<repo-name>
          external-repo-branch: gh-pages # defaults to master
          deploy-token: ${{ secrets.PRIVATE_TOKEN}}

      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
