name: Build and publish python package

on:
  release:
    branches: [publish]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          POETRY_VERSION: "1.3.2"
          PYTHON_VERSION: "3.10"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
